services:
  app:
    build:
      context: .
      target: test

    environment:
      - MONGODB_URI=mongodb://mongodb:27017/attendence-system
      - JWT_SECRET_KEY=secretkey
    depends_on:
      - mongodb
    command: sh -c "npm run dev & sleep 10 && npm run test"

  mongodb:
    image: mongo:7.0
    tmpfs:
      - /data/db
